import Head from "next/head";
import { Form } from "~/components/Form";
import { ListTodo } from "~/components/ListTodo";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
import Link from "next/link";
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Form />
    <ListTodo />
    </>
  );
}
{/* <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
    </main> */}
